### ISSUE TITLE
pratica 01

### ISSUE THREAD

**Issue by Lucas-Pavao** [Lucas-Pavao/GCMS-Lucas-Pavao-#1]
https://github.com/Lucas-Pavao/GCMS-Lucas-Pavao-/blob/main/README.md

**Comment by ramidedantas** [comment]
@Lucas-Pavao veja na prática o formato de link que pedi para ser usado. 

Modifique o Readme para ficar parecido com o que botei no meu repositório. Me marque aqui quando tiver feito, para eu adicionar meu nome.

**Comment by Lucas-Pavao** [comment]
@ramidedantas

**Comment by ramidedantas** [comment]
Alteração realizada, pode fechar a issue.
